### ISSUE TITLE
fix: token rotation not functioning as expected

### ISSUE THREAD

**Issue by jim80net** [CogniQ/CogniQ#72]
**Describe the bug**
Token rotation fails with 

```
cogniq.slack.cogniq_slack - ERROR - Failed to rotate tokens due to The request to the Slack API failed. (url: https://www.slack.com/api/oauth.v2.access)
2023-06-25T01:27:46.657944826Z The server responded with: {'ok': False, 'error': 'invalid_refresh_token'}
```
It appears that [rotation](https://github.com/slackapi/python-slack-sdk/blob/12e485095908199aa8272367f6bfff25efcf5829/slack_sdk/oauth/token_rotation/async_rotator.py) is not occurring. 

**Expected behavior**
The tokens should be [refreshed](https://github.com/slackapi/python-slack-sdk/blob/12e485095908199aa8272367f6bfff25efcf5829/slack_sdk/oauth/token_rotation/async_rotator.py)

**Comment by jim80net** [comment]
QA fail. still not working.

**Comment by jim80net** [comment]
Here's another stack trace: 

```
2023-07-02 07:14:58,151 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-13' coro=<Evaluator.ask_task() done, defined at /home/jim/workspace/github.com/CogniQ/CogniQ/cogniq/personalities/evaluator/evaluator.py:56> exception=SlackApiError("The request to the Slack API failed. (url: https://www.slack.com/api/chat.update)\nThe server responded with: {'ok': False, 'error': 'token_revoked'}")>
Traceback (most recent call last):
  File "/home/jim/workspace/github.com/CogniQ/CogniQ/cogniq/personalities/evaluator/evaluator.py", line 105, in ask_task
    await buffer_and_post_task  # ensure buffer_and_post task is finished
  File "/home/jim/workspace/github.com/CogniQ/CogniQ/cogniq/personalities/evaluator/evaluator.py", line 114, in buffer_and_post
    await self.cslack.chat_update(
  File "/home/jim/workspace/github.com/CogniQ/CogniQ/cogniq/slack/cogniq_slack.py", line 214, in chat_update
    raise e
  File "/home/jim/workspace/github.com/CogniQ/CogniQ/cogniq/slack/cogniq_slack.py", line 186, in chat_update
    await self.app.client.chat_update(
  File "/home/jim/.pyenv/versions/3.10.10/envs/venv/lib/python3.10/site-packages/slack_sdk/web/async_client.py", line 2351, in chat_update
    return await self.api_call("chat.update", json=kwargs)
  File "/home/jim/.pyenv/versions/3.10.10/envs/venv/lib/python3.10/site-packages/slack_sdk/web/async_base_client.py", line 161, in api_call
    return await self._send(
  File "/home/jim/.pyenv/versions/3.10.10/envs/venv/lib/python3.10/site-packages/slack_sdk/web/async_base_client.py", line 201, in _send
    return AsyncSlackResponse(**{**data, **res}).validate()
  File "/home/jim/.pyenv/versions/3.10.10/envs/venv/lib/python3.10/site-packages/slack_sdk/web/async_slack_response.py", line 203, in validate
    raise e.SlackApiError(message=msg, response=self)
slack_sdk.errors.SlackApiError: The request to the Slack API failed. (url: https://www.slack.com/api/chat.update)
The server responded with: {'ok': False, 'error': 'token_revoked'}
```

**Comment by jim80net** [comment]
At this point, it appears that the bot is able to consistently renew its token. It seems to wait until the token is expired, but it does renew. While not perfect, I'm closing this issue until that becomes a problem.
